# README

This is the site holding the contents and configuration for generating.

- [perl-workflow.github.io](https://perl-workflow.github.io) / [workflow.pm](https://workflow.pm) in the perl-workflow.github.io repository

Currently the website is based on [mkdocs](https://www.mkdocs.org/).

The site is generated from the perl-workflow.github.io repo like so:

```shell
cd ../perl-workflow.github.io/
mkdocs gh-deploy --config-file ../website/mkdocs.yml --remote-branch main
```

When deployed, the site is available at:

- [Workflow.pm](https://workflow.pm/) and [perl-workflow.github.io](https://perl-workflow.github.io), the latter being the GitHub Pages URL.

The perl-workflow.github.io repository is a mirror of the website repository and it auto-generated by the mkdocs command above.

Content changes are made in the website repository. Do note the `CNAME` specification is also in the website repository togehter with the MkDocs configuration file, which outlines the website structure and content.

If the CNAME record is not set, the site will be available at the GitHub Pages URL.

- [perl-workflow.github.io](https://perl-workflow.github.io)

If it is set, the site will be available at the CNAME URL.

- [Workflow.pm](https://workflow.pm/) and the GitHub Pages URL is not used and the website is just presented under the CNAME.

MkDocs documentation available at:

- [MkDocs](https://www.mkdocs.org/)
- [MkDocs: "deploying your documentation"](https://www.mkdocs.org/user-guide/deploying-your-docs/)
- [GitHub Pages: "Configuring a custom domain for your GitHub Pages site"](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site)
